FROM node:22-alpine

RUN npm install -g pnpm@9.14.2

WORKDIR /app

RUN apk --no-cache add git \
    && rm -rf /var/cache/apk/*

# COPY ./package*.json /app/

COPY . .

RUN chown -Rf node:node /app

USER node

RUN rm -Rf ./{.nuxt,.output,node_modules}

RUN pnpm config set store-dir /app/.local/share/pnpm/store/v3 --global \
    && pnpm install

ENV PATH ./node_modules/.bin/:$PATH
